#!/bin/bash
#
#   Erstellt ein oder mehrere Kubernetes Cluster. 
#   Die Anzahl Worker Nodes richtet sich an den Anzahl KVM-Pods, Master auf 1. Pod und pro Pod ein Worker.
#   Ein Suffix, wird im Gegensatz zu normalen VMs, nicht unterstuetzt.
#

[ $# -lt 2 ] || [ ! -f $1 ] && { echo createk8svms config modul anzahl; exit 1; }

# einfacher YAML Parser von https://stackoverflow.com/questions/5014632/how-can-i-parse-a-yaml-file-from-a-linux-shell-script
function parse_yaml 
{
   local prefix=$2
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=%s\n", "'$prefix'",vn, $2, $3);
      }
   }'
}

################### Argumente Auswerten ###################

if  [ -f $1 ]
then

# config.yaml parsen und als config_xxxx Umgebungsvariablen setzen
for e in $(eval parse_yaml $1 | grep "^$2" | sed "s/^$2/config/")
do
    export $e
done
fi

[ $# -gt 2 ] && [ $3 -ne 0 ] && COUNT=$3 || COUNT=${config_vm_count}
POOLNAME="$2"
OFFSET=1

################### MAAS Interaktion ###################

PODS=$(maas $PROFILE pods read | jq '.[] | .name' | wc -l)
POOL=$(maas $PROFILE resource-pools read | jq ".[] | select (.name==\"${POOLNAME}\") | .id")

if [ "${POOL}" == "" ]
then
    maas $PROFILE resource-pools create name=${POOLNAME}
    POOL=$(maas $PROFILE resource-pools read | jq ".[] | select (.name==\"${POOLNAME}\") | .id")
    if [ "${POOL}" == "" ]
    then
        echo "Error: kann Resource Pool nicht erstellen"
        exit 1
    fi
fi

MODUL=$2

# Master
for pod in $(maas $PROFILE pods read | jq '.[] | .id' | head -n +1)
do
    counter=1
    c=${COUNT}
    while   [ ${c} -gt 0 ] && [ ${counter} -le ${COUNT} ]
    do    
        c=$((${c} - 1))
        HOSTNAME=$(printf "%s-%02d" ${MODUL} $((${counter} + ${OFFSET})))
        echo maas $PROFILE pod compose ${pod} memory=${config_vm_memory} cores=${config_vm_cores} storage=${config_vm_storage} pool=${POOL} hostname=${HOSTNAME}
        maas $PROFILE pod compose ${pod} memory=${config_vm_memory} cores=${config_vm_cores} storage=${config_vm_storage} pool=${POOL} hostname=${HOSTNAME}
        counter=$((${counter} + 1))
    done
done

# Konfiguration fuer Worker laden
MODUL=$(echo $2 | sed 's/master/worker/g')
for e in $(eval parse_yaml $1 | grep "^${MODUL}" | sed "s/^${MODUL}/config/")
do
    export $e
done  
   
# Worker    
for pod in $(maas $PROFILE pods read | jq '.[] | .id' | tail -n +2)
do
    counter=1
    c=${COUNT}
    while   [ ${c} -gt 0 ] && [ ${counter} -le ${COUNT} ]
    do    
        c=$((${c} - 1))
        HOSTNAME=$(printf "%s-%02d-%d" ${MODUL} $((${counter} + ${OFFSET})) ${pod} )
        echo maas $PROFILE pod compose ${pod} memory=${config_vm_memory} cores=${config_vm_cores} storage=${config_vm_storage} pool=${POOL} hostname=${HOSTNAME}
        maas $PROFILE pod compose ${pod} memory=${config_vm_memory} cores=${config_vm_cores} storage=${config_vm_storage} pool=${POOL} hostname=${HOSTNAME}
        counter=$((${counter} + 1))
    done
done    
