#!/bin/bash
#
#	Installationsscript
#
#	Ausfuehren als User ubuntu in dessen HOME Verzeichis
#
#	@see: https://github.com/mc-b/lernmaas/blob/master/doc/MAAS/Install.md

#######
# SW Update und Installation fehlende SW

sudo apt update
sudo apt upgrade -y
sudo apt install -y jq markdown nmap traceroute wsmancli git curl wget vino remmina

#######
# MAAS Installation und Konfiguration

sudo add-apt-repository ppa:maas/stable -y  
sudo apt install -y maas

sudo maas init --admin-username ubuntu --admin-password password --admin-email marcel.bernet@tbz.ch
cat <<%EOF% >>$HOME/.bashrc
export PROFILE=ubuntu
%EOF%

#######
# SSH Key und Konfiguration

ssh-keygen -t rsa -f .ssh/id_rsa -b 4096 -P ''    

cat <<%EOF% >/home/ubuntu/.ssh/config
StrictHostKeyChecking no
UserKnownHostsFile /dev/null
LogLevel error
%EOF%

sudo sysctl -w  net.ipv4.ip_forward=1
# sed -e     sudo vi /etc/sysctl.conf

#######
# Shared Folder anlegen

sudo mkdir -p /data /data/storage /data/config /data/templates /data/config/wireguard /data/config/ssh /data/templates/cr-cache
sudo chown -R ubuntu:ubuntu /data
sudo chmod 777 /data/storage
    
#######
# NFS

sudo apt install -y nfs-kernel-server

# Zugriff fuer Subnetze (10.0.31.0 = eigenes Subnets, 10.244.0.0 = Kubernetes/flannel) freischalten
    
cat <<%EOF% | sudo tee /etc/exports
# /etc/exports: the access control list for filesystems which may be exported
#               to NFS clients.  See exports(5).
# Storage RW
/data/storage 10.0.38.0/24(rw,sync,no_subtree_check,all_squash,anonuid=1000,anongid=1000)
/data/storage 10.244.0.0/16(rw,sync,no_subtree_check,all_squash,anonuid=1000,anongid=1000)
# Templates RO
/data/templates 10.0.38.0/24(ro,sync,no_subtree_check)
/data/templates 10.244.0.0/16(ro,sync,no_subtree_check)
# Config RO
/data/config 10.0.38.0/24(ro,sync,no_subtree_check)
/data/config 10.244.0.0/16(ro,sync,no_subtree_check)
%EOF%
     
sudo exportfs -a
sudo systemctl restart nfs-kernel-server
   
#######
# Preseeds MAAS und Helper Scripts 

git clone https://github.com/mc-b/lernmaas.git
sudo chmod +x lernmaas/helper/*
sudo cp lernmaas/helper/* /usr/local/bin/
sudo cp /home/ubuntu/lernmaas/preseeds/* /var/snap/maas/current/preseeds/

#######
# WireGuard + SSH
sudo apt-get install -y wireguard openssh-server net-tools

cat <<%EOF% | sudo tee /etc/wireguard/wg0.conf
%EOF%
[Interface]
Address = 10.9.38.250/24
PrivateKey = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

[Peer]
PublicKey = bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
Endpoint = gateway:51820

AllowedIPs = 10.9.38.0/24

# This is for if you're behind a NAT and
# want the connection to be kept alive.
PersistentKeepalive = 25
%EOF%

sudo chown -R root:root /etc/wireguard
sudo chmod 750 /etc/wireguard
sudo chmod 640 /etc/wireguard/wg0.conf

sudo systemctl enable wg-quick@wg0.service
sudo systemctl start wg-quick@wg0.service

######
# Aufraeumen

sudo apt autoremove -y
