apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lernmaas
  namespace: mc-b
  description: MAAS / IAAS Umgebung um Cluster von VMs oder Kubernetes auszusetzen
  tags:
  - maas
  - tbz
  - lernkube
  - kubernetes
  - lernmaas
  links:
  - url: https://github.com/mc-b/lernmaas
    title: Repository
    icon: github
  annotations:
    github.com/project-slug: mc-b/lernmaas
    backstage.io/source-location: url:https://github.com/mc-b/lernmaas
    backstage.io/techdocs-ref: url:https://github.com/mc-b/lernmaas
spec:
  type: website
  lifecycle: production
  owner: group:mc-b/mc-b
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m100
  description: 'Modul 100: Daten charakterisieren, aufbereiten und auswerten'
  tags:
  - nfs
  - wireguard
  - ssh
  - samba
  links:
  - url: https://github.com/tbz-it/M100
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m104
  description: ''
  tags:
  - nfs
  - k8s
  - wireguard
  - samba
  links:
  - url: https://github.com/tbz-it/M104
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m120
  description: 'Modul 120: Benutzerschnittstellen implementieren'
  tags:
  - nfs
  - wireguard
  - ssh
  - samba
  links:
  - url: https://github.com/tbz-it/M120
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m122
  description: 'Modul 122: Automatisieren mit Skripten'
  tags:
  - nfs
  - wireguard
  - ssh
  - samba
  links:
  - url: https://github.com/tbz-it/M122
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m129
  description: 'Modul 129: LAN-Komponenten in Betrieb nehmen (nach Erstellung ''enablevminvm
    m129'' laufen lassen). Verbinden mittels GNS3 Desktop <IP>:3080'
  tags:
  - nfs
  - wireguard
  - ssh
  links:
  - url: https://github.com/tbz-it/M129
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m141
  description: 'Modul 141: Datenbanksystem in Betrieb nehmen'
  tags:
  - nfs
  - docker
  - k8s
  - wireguard
  - ssh
  - samba
  links:
  - url: https://github.com/tbz-it/M141
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m145
  description: 'Modul 145: Netzwerk betreiben und erweitern (nach Erstellung ''enablevminvm
    m145'' laufen lassen). Verbinden mittels GNS3 Desktop <IP>:3080'
  tags:
  - nfs
  - wireguard
  - ssh
  links:
  - url: https://github.com/tbz-it/M145
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m152
  description: 'Modul 152: Multimedia-Inhalte in Webauftritt integrieren'
  tags:
  - nfs
  - wireguard
  - ssh
  - samba
  links:
  - url: https://github.com/tbz-it/M152
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m153
  description: ''
  tags:
  - nfs
  - k8s
  - wireguard
  - samba
  links:
  - url: https://github.com/tbz-it/M153
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m158
  description: "Modul 158: Software-Migration planen und durchf\xFChren"
  tags:
  - nfs
  - wireguard
  - ssh
  - samba
  links:
  - url: https://github.com/tbz-it/M158
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m182
  description: ''
  tags:
  - nfs
  - wireguard
  - ssh
  links:
  - url: https://github.com/tbz-it/M182
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m183
  description: 'Modul 183: Applikationssicherheit implementieren (Kubernetes und Webgoat)'
  tags:
  - nfs
  - k8s
  - wireguard
  links:
  - url: https://github.com/tbz-it/M183
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m226
  description: 'Modul 226: Objektorientiert implementieren (Kubernetes mit 24 x BeakerX
    gestartet)'
  tags:
  - nfs
  - docker
  - k8s
  - wireguard
  - ssh
  - samba
  links: []
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m239
  description: 'Modul 239: Internet Server in Betrieb nehmen'
  tags:
  - nfs
  - wireguard
  - ssh
  - samba
  links:
  - url: https://github.com/tbz-it/M239
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m242
  description: 'Modul 242: Mikroprozessoranwendung realisieren'
  tags:
  - nfs
  - docker
  - wireguard
  - ssh
  links:
  - url: https://github.com/tbz-it/M242
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m254
  description: ''
  tags:
  - nfs
  - k8s
  - wireguard
  - ssh
  links:
  - url: https://github.com/tbz-it/M254
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m300
  description: 'Modul 300: Plattformuebergreifende Dienste in ein Netzwerk integrieren'
  tags:
  - nfs
  - docker
  - k8s
  - wireguard
  - ssh
  links: []
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m169
  description: 'Modul 169: Services mit Containern bereitstellen'
  tags:
  - nfs
  - docker
  - k8s
  - wireguard
  - ssh
  links:
  - url: https://github.com/tbz-it/M169
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m321
  description: "Modul 321: Verteilte Systeme analysieren, verstehen, planen, erweitern\
    \ und anwenden, sowie bestehende Applikationen in ein verteiltes System \xFCberfuehren."
  tags:
  - nfs
  - docker
  - k8s
  - wireguard
  - ssh
  links:
  - url: https://github.com/stefan-kemper/M321
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m347
  description: 'Modul 347: Dienst mit Container anwenden'
  tags:
  - nfs
  - docker
  - k8s
  - wireguard
  - ssh
  links:
  - url: https://github.com/tbz-it/M347
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m426
  description: ''
  tags:
  - nfs
  - docker
  - k8s
  - wireguard
  - ssh
  links:
  - url: https://github.com/tbz-it/M426
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-m437
  description: ''
  tags:
  - nfs
  - k8s
  - wireguard
  links:
  - url: https://github.com/tbz-it/M437
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-microk8s
  description: microk8s Kubernetes Umgebung
  tags:
  - nfs
  - k8s
  - wireguard
  - ssh
  links: []
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: lernmaas-gns3
  description: 'Modul GNS3: Netzwerk betreiben und erweitern'
  tags:
  - nfs
  - wireguard
  - ssh
  links:
  - url: https://github.com/mc-b/lerngns3
  namespace: tbz
spec:
  type: script
  lifecycle: production
  owner: tbz/it-grundbildung
  providesApis: []
  dependencyOf: component:mc-b/lernmaas
