site_name: lernmaas
site_description: 'MAAS / IAAS Umgebung um Cluster von VMs oder Kubernetes auszusetzen'
repo_url: https://github.com/mc-b/lernmaas
edit_uri: edit/master/docs

docs_dir: doc

plugins:
  - techdocs-core
        
nav:
  - Einleitung: index.md
  - Installation:
      - MAAS Master und Worker Nodes: MAAS/Install.md
      - Gateway Server: MAAS/Gateway.md
      - Einbinden der Clients und Portweiterleitung: MAAS/GatewayClient.md
      - Virtualisierte Machinen in Virtualisierten Machinen: MAAS/VMinVM.md
      - Public Cloud und lernMAAS: Cloud/README.md
      - Proxmox und lernMAAS: Proxmox/README.md
      - GNS3 und lernMAAS: GNS3/README.md
      - Lokaler PC mit Vagrant und lernMAAS: vagrant/README.md
  - Fragen und Antworten:
    - FAQ: MAAS/FAQ.md
