#!/bin/bash
#
#   MAAS: gibt die Maschinen aus

zu langsam

bei makekey gleich Datei mit hostnamen und ip Adresse rausschreiben


for M in $(maas $PROFILE machines read | jq -c -r -M '.[] | .system_id')
do
# TODO Status abfragen ob Power On und Deployed (28)

    V=$(maas $PROFILE machine read ${M} | jq -c -r -M '.hostname, .pool.name, .ip_addresses')
    echo $V | awk '{ printf("Host: %s, Pool %s, IP: %s\n", $1, $2, $3) }'
done


SSH Timeout

Use the -o ConnectTimeout and -o BatchMode=yes -o StrictHostKeyChecking=no 