#!/bin/bash
#
#   Fixe IP Adresse fuer maas-Rackserver Template

cat <<EOF | sudo tee /etc/netplan/50-cloud-init.yaml
# This file is generated by https://raw.githubusercontent.com/mc-b/lerngns3/master/scripts/maas-network.sh. 
network:
    ethernets:
        enp1s0:
            addresses:
            - 192.168.122.8/24
            dhcp4: false
            dhcp4-overrides:
               use-dns: false
            dhcp6: false
            gateway4: 192.168.122.1
            nameservers:
                addresses:
                - 208.67.222.222
                - 208.67.220.220
    version: 2
EOF

sudo netplan generate
